### ISSUE TITLE
Search Bar is missing in Vue Data Table

### ISSUE THREAD

**Issue by naishu** [laravel-enso/tables#144]
**Help needed.**

### Prerequisites
*  Are you running the latest version? Yes
*  Are you reporting to the correct repository? Yes
*  Did you check the documentation? Yes
*  Did you perform a cursory search? Yes

### Description

The Search bar doesn't appears in the Vuedatatable. I'm using this outside the enso ecosystem. Using this in the blade view file in laravel

< vue-table :path="'table/init'"        
    id = "user"      
    /> 

![image](https://user-images.githubusercontent.com/4885062/55639596-5e90d280-578f-11e9-869a-394c3894cee0.png)

### Expected behavior
Search Bar to Appear. Also there is no error in the console

![image](https://user-images.githubusercontent.com/4885062/55639806-dc54de00-578f-11e9-8c75-c39829dcaa88.png)

![image](https://user-images.githubusercontent.com/4885062/55639851-eecf1780-578f-11e9-832b-b5f766098091.png)

Also the init json response has searchable:true

![image](https://user-images.githubusercontent.com/4885062/55639913-1f16b600-5790-11e9-971f-fb73144a6de6.png)

Config.json file is as follows.

`{
    "routePrefix": "table",

    "crtNo": false,
    "cache": true,
    "flatten": false,
    "auth": false,
    "debounce": 100,
    "lengthMenu": [10, 15, 20, 25, 30],
     "selectable": false,
    

    "comparisonOperator": "LIKE",
       "columns": [
      
        {
            "label": "Course Name",
            "data": "inactive.COURSE_NAME",
            "name": "COURSE_NAME",
            "meta": ["searchable", "sortable"]
                  
        
        }
    
    
      
    ]
} 
  `

### Actual behavior
Search Bar doesn't Appear. I checked with the examples in the repository. I couldn't find anything other than adding searchable in meta field.

**Comment by aocneanu** [comment]
What version are you using?

Could you paste here the full response from `table/init` ?

**Comment by naishu** [comment]
Version = "@enso-ui/tables": "^1.0.31",

Response from table/init 

`{"template":{"crtNo":false,"cache":true,"flatten":false,"auth":false,"debounce":100,"lengthMenu":[10,15,20,25,30],"selectable":false,"columns":[{"label":"Course Name","data":"inactive.COURSE_NAME","name":"COURSE_NAME","meta":{"searchable":true,"sortable":true,"translatable":false,"boolean":false,"slot":false,"rogue":false,"total":false,"date":false,"icon":false,"clickable":false,"customTotal":false,"notExportable":false,"nullLast":false,"visible":true,"hidden":false,"sort":null}}],"buttons":{"global":[],"row":[]},"readPath":"\/bbfacultyalerts\/table\/Data","method":"GET","responsive":true,"labels":{"crtNo":"#","actions":"Actions"},"pathSegment":"table","actions":false,"align":"has-text-centered","style":"is-hoverable","aligns":{"center":"has-text-centered","left":"has-text-left","right":"has-text-right"},"styles":{"compact":"is-narrow","hover":"is-hoverable","striped":"is-striped","bordered":"is-bordered"},"highlight":"has-background-info"},"meta":{"comparisonOperator":"LIKE","fullInfoRecordLimit":1000000,"start":0,"search":"","loading":false,"forceInfo":false,"searchable":true,"sort":false,"total":false,"date":false,"translatable":false,"enum":false,"money":false},"apiVersion":"3.0"}`

**Comment by aocneanu** [comment]
In the meta section you have `searchable: true`.

Check please in vue dev tools in `TopControls` state.meta.searchable ' s value

![image](https://user-images.githubusercontent.com/16073274/56846363-28022f80-68d7-11e9-8f37-78f8fe72f95e.png)

If that's also `true` than I really can't understand what's happening because the search input is rendering is conditioned by this [flag](https://github.com/enso-ui/tables/blob/master/src/bulma/parts/top/Controls.vue#L55)

**Comment by webmvsn** [comment]
I have the same Problem with 2.0.10. Everything else works fine.  Under TopControls i have no State Object.

**Comment by aocneanu** [comment]
Upgrade to the latest version and if you still encounter problems reopen this issue
