### ISSUE TITLE
[Feature request] Add an option for expandable row

### ISSUE THREAD

**Issue by BKirev** [laravel-enso/tables#148]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Hey!
I'm trying to wrap my head around having an expandable rows in the table. Just like how we're able to click on the plus sign when there's not enough space for all columns to fit in.
But instead, it can show additional information. I'll use my use-case as an example:
I have a table with orders and it'll be really useful if I can click on the expand button and be able to see the products included in the given order. Thinking about server side, they can be pre-loaded or loaded on demand(expanding the row).

I'm sorry if there's already a way to do this easy enough and I just can't find/think about it. The hard life of a backend dev getting his feet wet in the frontend world.

### Expected behavior

An expand button to show additional info for the clicked record. Pre-loaded or on demand.

### Actual behavior

The plus sign(expand button) shows columns that are not able to fit on the screen.

**Comment by aocneanu** [comment]
This sounds like an interesting addition.

We could have a meta option, something like `preview`, that will allow when clicking a control creating a new row with a slot where we would have the option to put whatever we want.

We could also add the option to render the table with the `preview` expanded or collapsed...

When I will have the time I will add this.

**Comment by aocneanu** [comment]
You can now have a `"preview": true` in the json template. This will generate a preview slot that you can populate in the table

```js
<vue-table ....>
    <template name:preview="{ row }">
          <async-component :model="row.dtRowId"/>
    </template>
</vue-table>
```

@gandesc remember to document this

**Comment by gandesc** [comment]
added information about the new feature to the docs.
