### ISSUE TITLE
[Question] How to pass an object from Laravel blade view to table component?

### ISSUE THREAD

**Issue by jammy-git** [laravel-enso/tables#150]
This is  a question.

The `params` parameter for the tables component is of type object, but I can't see that it is possible to pass an object from a Laravel blade template file when initialising the tables Vue component?

I thought it would be something like:

    <vue-table params='@json(["param1" => $param1])'></vue-table>

However this causes it to be passed as a string.

**Comment by aocneanu** [comment]
I guess you forgot the `:` before params => `:params`, but this is not related to Enso at all.
