### ISSUE TITLE
refactor made $this->request an Obj

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/tables#151]
This is  a **documentation/changelog issue**.

### Prerequisites
3.3 enso upgrade

### Description

If you use/require params in the table query, the syntax got changed (or I'm doing something wrong 😁 )

![image](https://user-images.githubusercontent.com/932193/58313844-c918d300-7e0e-11e9-8b5c-23e5098c236e.png)

**Comment by aocneanu** [comment]
The Obj was refactored to extend `Collection` so you can't use `$obj->prop`.

**Comment by jlsjonas** [comment]
🤔 Looks like my IDE is playing tricks on me...
when I debugged that line I could receive the same by executing `json_decode($this->request->get('params'))`

HOWEVER, when I actually replaced the line and ran it again, that indicates that `Property [params] does not exist on this collection instance`

**Comment by jlsjonas** [comment]
It appears to have been a _glitch in the Matrix_ 😅 

i'll leave this open for inclusion in the changelog.
