### ISSUE TITLE
tableDate request fails if it is a post request without using intervals

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/tables#153]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I guess that a request is automatically done as post request if query is to big for get request.
I'm not using intervals in this table.

### Steps to Reproduce
1. Create a table with a lot of query params (e.g. filters, ...)
2. Try to open table

### Expected behavior

No exception.

### Actual behavior

Exception:
```
{
    "message": "Call to a member function each() on null",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/var/www/html/vendor/laravel-enso/tables/src/app/Services/Table/Filters.php",
    "line": 91,
...
```

Reason: `$this->request->has('intervals')` is `true` because key is set in payload (`"intervals":null,`)

**Comment by robbykrlos** [comment]
`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function each() on null`

` Symfony\Component\Debug\Exception\FatalThrowableError
…\vendor\laravel-enso\tables\src\app\Services\Table\Filters.php93`

![image](https://user-images.githubusercontent.com/16973022/61945231-26b0d380-afa8-11e9-80c2-d1376a8cbda0.png)

I still experience the same issue.

**Comment by aocneanu** [comment]
the format should be:

```js
filters: {
      table: {
            column: [values]
      }
}
```

**Comment by robbykrlos** [comment]
I have a combination of select-filter with vue-filter (boolean). It seems for the second filter, the boolean one, the filter is null, and fails on ->each

I tried 
`
if($filters)
				$filters->each(.....
`

**Comment by robbykrlos** [comment]
> the format should be:
> 
> ```js
> filters: {
>       table: {
>             column: [values]
>       }
> }
> ```

Thank you
