### ISSUE TITLE
Count breaks when using multiple joins

### ISSUE THREAD

**Issue by degustadev** [laravel-enso/tables#154]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

When using multiple joins, the count of the table breaks and counts more results.
As you can see here is the response with count = 2
![response](https://user-images.githubusercontent.com/39300461/59361415-1adbbb80-8d32-11e9-85bf-5a44fe2c8970.png)

And here the rendered table with 1 result which is correct but it says 1 of 2 results, and with 1 result is ok, but when I have a lot of records it creates "ghost" pages to paginate a lot of non existing results.
![table](https://user-images.githubusercontent.com/39300461/59361591-64c4a180-8d32-11e9-97b0-adb39cc7cb56.png)

I'm using this query:

```php
$parts = explode('-', $params->filter->campaign);
$models = Product::select('user_contents.id as dtRowId', 'user_contents.id', 'user_contents.url', 'user_contents.visits_reach', 'user_contents.approved', 'user_contents.highlighted', 'user_contents.month', 'social_media_profiles.name')
                    ->distinct()
                    ->join('user_product', 'products.id', '=', 'user_product.product_id')
                    ->join('user_contents', 'user_contents.id', '=', 'user_product.user_content_id')
                    ->join('users', 'user_contents.user_id', '=', 'users.id')
                    ->join('social_media_profiles', 'user_contents.social_media_profile_id', '=', 'social_media_profiles.id')
                    ->whereNull('users.role_id')
                    ->where(function ($query) use ($parts, $params) {
                        $query->where([['products.year', '=', $parts[0]], ['products.month', '=', $parts[1]]])
                            ->orWhere('user_contents.month', '=', $params->filter->campaign);
                    })
                    ->with('user');
```

As you can see I'm using `params` to filter the results based on some external filters because I use manual tables. But well in the end should be the same.

### Expected behavior

The package counts correctly the number of returned records

### Actual behavior

The package counts incorrectly the number of returned records

**Comment by degustadev** [comment]
Ops, I see there's already an open ticket about this: https://github.com/laravel-enso/tables/issues/152

**Comment by aocneanu** [comment]
Distinct `affects` Laravel's query builder the same way `groupBy` does. Follow the discussion [here](https://github.com/laravel-enso/tables/issues/152)
