### ISSUE TITLE
Customize WHERE clause for vue-filter

### ISSUE THREAD

**Issue by scarneros** [laravel-enso/tables#156]
This is  a **feature request** is there's no other way to do it.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I need to filter 'banned_at' column on users table, this column is NULL or contains the date when user was banned, for this purpose I have added a vue-filter on frontend:

```
<div class="column is-3">
    <vue-filter
        class="box"
        title="Status"
        icons
        :options="activeOptions"
        v-model="filters.users.banned_at">
    </vue-filter>
</div>

...

data() {
   return {
       filters: {
            users: {
                banned_at: null,
            },
        },
        activeOptions: [
            { value: true, icon: 'user-check', class: 'has-text-success' },
            { value: false, icon: 'user-slash', class: 'has-text-danger' },
        ],
   }; 
}
```

And this on template JSON file:

```
...
{
    "label": "Active",
    "data": "activeStatus",
    "name": "active",
    "meta": [
        "boolean",
        "rogue"
    ]
}
...
```

On the database side I used 'CASE' statement to cast 'banned_at' column into boolean:

```
...
public function query()
{
    return User::select(DB::raw(
        'users.id as "dtRowId",
        users.name,
        companies.name as "company",
        users.email,
        users.phone,
        (CASE WHEN users.banned_at IS NULL THEN 1 ELSE 0 END) as "activeStatus"'
    ))
        ->join('companies', 'users.company_id', '=', 'companies.id', 'left outer');
}
...
```

This works pretty well as it returns boolean values to the vue-datatable frontend (just as I needed), but the filter tries to compare 'banned_at' column with true or false and evidently fails. This is the SQL statement the filter is sending:

`... WHERE (users.banned_at in (0)) ...`

And this is the statement that should be sent to make it work (or something similar):

`... WHERE ((CASE WHEN users.banned_at IS NULL THEN 1 ELSE 0 END) in (0)) ...`

The question is, is there any way to achieve that? Any recommendations in what to do?

**Comment by aocneanu** [comment]
Use the `params` object instead of `filters` for this attribute.

In the TableBuilder you  have access to `$this->request()->get('params')`.

In your query add `->whereRaw('your statement')` and use in your statement the attribute extracted from the params object

**Comment by scarneros** [comment]
Thanks for the ultra-fast response Adrian, it works like a charm!

The only thing I miss is the record counter, at this time it only shows the records filtered as a total. Any hint on this?

**Comment by aocneanu** [comment]
There is no workaround for that at this moment.

On the next BE refactor we will have an `AfterCountFilter` contract that will allow this.

**Comment by scarneros** [comment]
Ok, I'll close the issue as the main question was resolved.

Thanks.

**Comment by aocneanu** [comment]
@scarneros  starting with v2.2.2 you can add a `protected afterCount($query)` in your table builder class. make sure you return the altered query from this method.
