### ISSUE TITLE
Number interval filters not working

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/tables#157]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Number interval filters are not working because in `Filters.php` it tries to format the number as date

In `src/app/Services/Table/Filters.php` on Line 123 and 145 you are using the following
```
        $dateFormat = $value->get('dateFormat')
            ?? config('enso.config.dateFormat');
```
- If `$value->get('dateFormat')` is undefined (e.g. for number values) it uses the date format from config
- On line 128 and 150 you are checking if `$dateFormat` is set and if yes, you are treating the value as date which leads to the following exception:

<img width="982" alt="Screenshot 2019-07-05 13 12 14" src="https://user-images.githubusercontent.com/7204559/60718976-87f40280-9f26-11e9-85f0-66a3a461b8f7.png">

**Comment by aocneanu** [comment]
@vmcvlad , @ionutcatalinsandu , @gandesc , from now on `dbDateFormat` is mandatory when using date interval filters with tables.

also `interval-filter` now takes a `v-model="interval"` where `interval` is an object that has to have `min` & `max` props.

@gandesc please pin this and remember to update the docs in tables / filters.

**Comment by aocneanu** [comment]
@mauthi the issue(s) is (are) fixed, thanks for reporting ;)

**Comment by mauthi** [comment]
thx
you are welcome

**Comment by gandesc** [comment]
added note in the docs

**Comment by mauthi** [comment]
I tried this and found the following problems:

Date interval filter
- I defined my model like
```
				      "entry_date": {
				        "min": null,
				        "max": null,
                        "dbDateFormat": 'Y-m-d',
				      }
```
- Request does not include `dbDateFormat`
`"intervals": "{"cash_book_entries":{"amount":{"min":null,"max":null},"entry_date":{"min":"10.06.2019","max":"11.07.2019"}}}"`

----

Number Interval Filter
- Both, x Buttons on MIN and MAX field clear the value of MIN Field

**Comment by aocneanu** [comment]
provide that code were you bind `entry_date` to the filter. Therein lies a problem.

**Comment by mauthi** [comment]
```
					    	 <enso-date-interval-filter
					            :title="i18n('Date Filter')"
					            default="all"
					            @update="intervals.cash_book_entries.entry_date = $event">
					    	</enso-date-interval-filter>
```

**Comment by aocneanu** [comment]
Change that to

```js
<enso-date-interval-filter
    :title="i18n('Date Filter')"
    default="all"
   @update="
         intervals.cash_book_entries.entry_date.min = $event.min
         intervals.cash_book_entries.entry_date.max = $event.max
"/>
```

and the original object will not be replaced

**Comment by aocneanu** [comment]
Meanwhile I'm looking at another approach...

**Comment by mauthi** [comment]
Works :)

The following is still open (no hurry - but as reminder that you didn't overlook it)
- Both, x Buttons on MIN and MAX field clear the value of MIN Field

**Comment by aocneanu** [comment]
>you didn't overlook

That's exactly what I did :)
