### ISSUE TITLE
Typo in namespace (Tabels)

### ISSUE THREAD

**Issue by GeoffreyMills** [laravel-enso/tables#158]
This is  a **bug request**.

### Prerequisites
* [ x ] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
* [x ] Did you check the documentation?
* [x ] Did you perform a cursory search?

### Description
FWIW Found a typo (Tabels) in the namespace in ModelsTable.php file under vendor, while trying to work out how this package works

../vendor/laravel-enso/tables/resources/Tables/Builders/ModelsTable.php

<?php

namespace App\Tabels\Builders;

Documentation issue I guess, don't know enough Laravel to comment otherwise. Hope it's useful,
Geoffrey

**Comment by aocneanu** [comment]
Thanks:)

[docs](https://docs.laravel-enso.com/backend/tables.html)

**Comment by aocneanu** [comment]
closed with 86adb0d
