### ISSUE TITLE
Table "column visibility" feature is rendering options above and beneath the bookmarks control

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/tables#162]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Table "column visibility" feature is rendering options above and beneath the bookmarks control

![image](https://user-images.githubusercontent.com/16973022/61641298-8dcc4080-aca7-11e9-9c29-ea55c7a92ff8.png)

### Steps to Reproduce
1. Using Firefox 68, with a screen resolution of 1366x768 and a data table with at least 8 columns.
2. click here:
![image](https://user-images.githubusercontent.com/16973022/61641474-dedc3480-aca7-11e9-8513-bde50c1b6ddf.png)
3. observe.

### Expected behavior
Render below, where is room to render all options

### Actual behavior
Renders above and beneath the bookmarks control.

**Comment by aocneanu** [comment]
Do you have the browser console open by any chance?

**Comment by robbykrlos** [comment]
I don't see anything special....

![image](https://user-images.githubusercontent.com/16973022/61713563-8e291200-ad61-11e9-861b-aaee1c738d28.png)

Is this what you wanted to see?
