### ISSUE TITLE
How to map values with font-awesome icons 

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/tables#163]
This is  a **bug**. (opened bug because of [this](https://docs.laravel-enso.com/frontend/tables.html#questions-issues) - _For questions and support please use the issues functionality for this package_

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Question : "is there a way to dynamically decide which icon to be displayed in a table based on the data received on that specific cell?"

I have this table:

![image](https://user-images.githubusercontent.com/16973022/61703743-e86aa880-ad4a-11e9-8413-df9cb2777119.png)

which in the database has these values:

![image](https://user-images.githubusercontent.com/16973022/61703769-f91b1e80-ad4a-11e9-8dbf-29007cacd503.png)

As you can see i tried different values because initially I did not know in what form the icon name was expected.
Icons are preloaded in the app.js so there is no issue with icon availability.

What I try to do is to map some data value with some icons names, so that if values is "OK" it will show icon "check-square".

Documentation found for table icon meta configuration : https://docs.laravel-enso.com/backend/tables.html#template

**Comment by aocneanu** [comment]
This is not a bug & icons are not preloaded in app.js.

Each page imports its needed icons.

All you have to do is import in the `Index.vue` file corresponding to your table the icons you need.

If you want to have all the icons available make sure to import all the icons globally (I wouldn't recommend such thing).

**Comment by robbykrlos** [comment]
> This is not a bug & icons are not preloaded in app.js.
> 
> Each page imports its needed icons.
> 
> All you have to do is import in the `Index.vue` file corresponding to your table the icons you need.
> 
> If you want to have all the icons available make sure to import all the icons globally (I wouldn't recommend such thing).

The problem is not the loading of the icons. I may have been incorrect in the way I wrote things... I wanted to point that the icon is not missing and this is not the problem.

I want to know if there is a way to map database values (not icon names) with fa icon names.
I feel I have no control on how the icon field is behaving, and was wondering if there are some hidden things that I might oversee.

I tried at some point also to use an alias for the FA imports
`
import {faCheckSquare as OK} from '@fortawesome/free-solid-svg-icons';

library.add(OK);
`
so that I could somehow trick the icon field into loading the corresponding icon 'check-square' for my incomming value 'OK'.

Didn't work.

**Comment by aocneanu** [comment]
Ah I got it now, inspect your menus table to see how we’re managing icons in db

**Comment by robbykrlos** [comment]
Ok somewhere around here:

menus.json
`
    "appends": ["computedIcon"],
    "cache": true,
    "columns": [
...        
        {
            "label": "Icon",
            "name": "computedIcon",
            "data": "menus.computedIcon",
            "meta": ["sortable", "icon"]
        }, 
...
`

Model :

`
...
public function getComputedIconAttribute()
    {
        return Str::contains($this->icon, ' ')
            ? explode(' ', $this->icon)
            : $this->icon;
    }
...
`


Thank you, i'll have a look on it.
