### ISSUE TITLE
Example for select-filter usage on tables

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/tables#164]
This is  a **question**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Is there a simple example / documentation for a simple table filter on some column? Scenario - a select drop-down for a table column which has already a options defined and it will just call a table reload filtering by the selected value.

Thank you

**Comment by aocneanu** [comment]
How is this a bug?!

[examples](https://www.laravel-enso.com/examples/table)

**Comment by robbykrlos** [comment]
Hi @aocneanu,

Thank you for the example.

This is not a bug, correct...

https://docs.laravel-enso.com/frontend/filters.html#questions-issues

_For questions and support please use the issues functionality for this package's github repository._

Should I update the documentation and suggest a specific tag? Or give an example of how a _question_ should not be following the given issue template.

**Comment by aocneanu** [comment]
No it's ok, it's not a common confusion.

**Comment by robbykrlos** [comment]
> How is this a bug?!
> 
> [examples](https://www.laravel-enso.com/examples/table)

Hi,

I'm playing around with the example you provided and I cannot find where exactly is the multi-select  table row option set in the code samples:

![image](https://user-images.githubusercontent.com/16973022/62055990-5a4c6180-b225-11e9-8df1-7ce2e599c90d.png)

Can you point it out in case I'm overseeing it...

Thank you & sorry for the stupid questions

**Comment by aocneanu** [comment]
LOL, I got it now.

Just add `selectable: true` in the tables json template

**Comment by robbykrlos** [comment]
Hi, 

Thanks for the answer - yes that was it:)

One more question though, if I want to add this `selectable: true` for one of enso's models (ex: permissions / roles) how do you recommend to proceed so that I don't change the vendor...

Thank you!

**Comment by aocneanu** [comment]
1. Create a local RoleTable that extends the one from the package and rewrite the path to a new template that will have the updated attributes.

2. In a local AppServiceProvider use `public $bindings = [EnsoRoleTable::class => LocalRoleTable:class]`

That's it

**Comment by robbykrlos** [comment]
aaa, ok the classic binding, thank you.
