### ISSUE TITLE
Illuminate\Http\Request in constructor of base Table class

### ISSUE THREAD

**Issue by shusharin** [laravel-enso/tables#165]
This is  a **feature request**.

### Prerequisites
* [+] Are you running the latest version?
* [+] Are you reporting to the correct repository?
* [+] Did you check the documentation?
* [+] Did you perform a cursory search?

### Description

Hi! Do you have plans to pass Illuminate\Http\Request in constructor of base Table class?
[Here](https://github.com/laravel-enso/tables/blob/master/src/app/Services/Table.php#L13)

This would be allow use other request resources. For example:
`$request->user()`

**Comment by aocneanu** [comment]
The Table class already has a `request()` method with all the params from the frontend (Obj)

If you want to access the user maybe you can use `auth()->user()`

**Comment by shusharin** [comment]
Yeah, i know about it.
But this approach does not allow use table object like source data outside from controller.

For example, let's do excel export with using queue job.

Then step by step:

1. Receive request for export xls from user
2. Make Export item (Model Export with some attrs), example: ![image](https://user-images.githubusercontent.com/5540885/62268061-411aff00-b437-11e9-8594-b96fe9a34767.png)
3. Put job for export in queue 
For job serialization we need:
- (object) Export (user.id inside)
- (string) class name for source data (Table class from controller)
- (array) request attributes ($request->all())
4. Response with Export  data (id, token for download, status of export building etc)
5. In queue job handler:
- make request object (Illuminate\Http\Request) & setUserResolver - user from Export object
- receive data from source - (new TableClass($request))->data() (in this call we can't use auth()->user()) 
- make xls file & change Export->status = done
6. User check status of export processing (for example send xhr request every 1 sec on exportController->check)
7. On frontend - show link on download when status done, or some error msg - you know

Yeah, i know how i can wrap Table object for implement this logic. But i think it will be better, implemented from in box this module.

**Comment by aocneanu** [comment]
All the above is already built in Enso via IO. Once you start an export you get push notifications (websockets) with the file export progress.

Ah, and for authorization purposes we have [this](https://github.com/laravel-enso/tables/blob/master/src/app/Jobs/ExcelExport.php#L34)

If you're using the package outside Enso and want to add support for new things you can work on a PR and we'll see where it goes.
