### ISSUE TITLE
translatable values of column

### ISSUE THREAD

**Issue by abufalbo** [laravel-enso/tables#168]
This is a feature request.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search? 

### Description
I would like to have translatable values in one column of the table. 
I have added the parameter `'meta' => ['translatable']`

Translation should be based on prop i18n. In documentation is only information about i18n prop:

> i18n, function, optional - the function that handles localisation

What should the i18n function look like? is there an example of use somewhere?

Thanks.

**Comment by aocneanu** [comment]
I'm expecting that you're using it outside Enso:

in template
```vue
<vue-table source="..."
    :i18n="i18n"/>
```
in methods
```vue
i18n(value) {
   // translate value
    return translatedValue;
}
```
