### ISSUE TITLE
Can't install on latest laravel version

### ISSUE THREAD

**Issue by jakob-fuchs** [laravel-enso/tables#173]
`composer require laravel-enso/tables` says at least Laravel 6.0 is required

**Comment by jakob-fuchs** [comment]
So there's no solution for this problem?

**Comment by aocneanu** [comment]
Please use in the future the issue template.

**Comment by jakob-fuchs** [comment]
Thanks for your help :+1:

**Comment by jakob-fuchs** [comment]
If anyone runs into the same problem:

The last version of this lib that supports the current Laravel version is 2.1.37

Using it is probably not advisable since it's not discernible from the docs which features are supported
