### ISSUE TITLE
Excel Export - Must be an instance of LaravelEnso\Core\app\Models\User, instance of App\User given

### ISSUE THREAD

**Issue by simplyaakif** [laravel-enso/tables#177]
This is  a **bug **.

### Prerequisites
* [x] Are you running the latest version?
Laravel Version: v6.0.0
Tables Version: v2.2.10
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
No mention of error in the documentation
* [x] Did you perform a cursory search?

### Steps to Reproduce
Install Laravel,
Install Tables,
Setup Auth for Users,
Set up Tables system using the Table builder and so on.

### Expected behavior

Excel File generated in exports folder. And mail recieved to download.

### Actual behavior

Error
![image](https://user-images.githubusercontent.com/26874542/67017135-bcc14980-f112-11e9-8054-05e78df3a48c.png)

Argument 1 passed to LaravelEnso\Tables\app\Jobs\ExcelExport::__construct() must be an instance of LaravelEnso\Core\app\Models\User, instance of App\User given, called in F:\Aakif Work\Websites\Managment\1 Ace Portal\vendor\laravel\framework\src\Illuminate\Foundation\Bus\Dispatchable.php on line 16"
trace: [{,…}, {,…}, {,…}, {,…},…]
0: {,…}
1: {,…}
2: {,…}
3: {,…}
4: {function: "__invoke", class: "App\Http\Controllers\QueryTableController", type: "->"}
5: {,…}
6: {,…}
7: {,…}
8: {,…}
9: {,…}
10: {,…}
11: {,…}
12: {,…}
13: {,…}
14: {,…}
15: {,…}
16: {,…}
17: {,…}
18: {,…}
19: {,…}
20: {,…}
21: {,…}
22: {,…}
23: {,…}
24: {,…}
25: {,…}
26: {,…}
27: {,…}
28: {file: "F:\Aakif Work\Websites\Managment\1 Ace Portal\vendor\fideloper\proxy\src\TrustProxies.php",…}
29: {,…}
30: {,…}
31: {,…}
32: {,…}
33: {,…}
34: {,…}
35: {,…}
36: {,…}
37: {,…}
38: {,…}
39: {,…}
40: {,…}
41: {file: "F:\Aakif Work\Websites\Managment\1 Ace Portal\public\index.php", line: 55, function: "handle",…}
42: {file: "F:\Aakif Work\Websites\Managment\1 Ace Portal\server.php", line: 21, function: "require_once"}

Also updating the reference of LaravelEnso\Core\app\Models\User with App\User removes the error but then occurs a new null kind of error.

**Comment by simplyaakif** [comment]
If possible kindly brief more or provide some resources to look into.

**Comment by simplyaakif** [comment]
Incase if i forgot to mention, i am using it outside enso ecosystem.

**Comment by aocneanu** [comment]
Ah I see!

**Comment by aocneanu** [comment]
use 5de334b48201481a741c1a7dadfe8e158cae1e72 (2.2.11)
