### ISSUE TITLE
Receive the parameters of the FE

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/tables#178]
This is  a **bug | feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

What is the way to receive the `$request` in the new version?. In the previous version I did it with: `json_decode($this->request->get('params'))`
I am migrating my tables to the new version and the previous form does not work :( and the documentation is not updated yet.

**Comment by aocneanu** [comment]
you receive now in the constructor a tables request with the following getters:

```
public function __construct (LaravelEnso\Tables\app\Services\Data\Request $request)
{
    $request->columns(): Obj
    $request->meta(): Obj
    $request->filters(): Obj
    $request->intervals(): Obj
    $request->params(): Obj
}
```
