### ISSUE TITLE
Laravel-enso works in 5.8?

### ISSUE THREAD

**Issue by alexsantm2019** [laravel-enso/tables#180]
Hi guys,
I have a question. Enso-tables work only with laravel 6.0?? This is because I have installed a project with laravel 5.8, but I can not install laravel-enso-tables.
If is possible to install in 5.8, what kind of steps I have to follow??

Thanks in advance

**Comment by aocneanu** [comment]
Hi @alexsantm2019,

You can install the latest version that supports L5.8.

You could also fork the last version and change in composer.json the requirement, and then figure out what changes you might do to make it work with 5.8, I don't expect there should be too much work. As long as we're concerned we are only focusing on supporting the latest versions of Laravel and VueJS.
