### ISSUE TITLE
Traits\Init fails to inject provided request to TableBuilder class

### ISSUE THREAD

**Issue by stotes** [laravel-enso/tables#188]
This is  a **bug**.

### Prerequisites
* [*] Are you running the latest version?
* [*] Are you reporting to the correct repository?
* [*] Did you check the documentation?
* [*] Did you perform a cursory search?

### Description
Line 15 of ```LaravelEnso\Tables\App\Traits\Init.php``` should inject the request object to the tableClass, however it fails to pass the request.

### Steps to Reproduce
Debug ```LaravelEnso\People\App\Tables\Builders\PersonTable.php``` after invoking Init and notice there is no request object in the class params. 

### Expected behavior
```$this->request``` should exist.

### Actual behavior
Request is missing.

**Comment by aocneanu** [comment]
Hi @stotes,

Describe how you tested it.

Note that the Init trait injects a [`LaravelEnso\Tables\App\Services\Data\Request`](https://github.com/laravel-enso/tables/blob/c375dfbac4e25da316f500fcf57f957245a6df3b/src/app/Services/Data/Request.php) object, not Laravel's request.

Make sure that you inspect this class to see the public interface.

**Comment by stotes** [comment]
> Hi @stotes,
> 
> Describe how you tested it.
> 
> Note that the Init trait injects a [`LaravelEnso\Tables\App\Services\Data\Request`](https://github.com/laravel-enso/tables/blob/c375dfbac4e25da316f500fcf57f957245a6df3b/src/app/Services/Data/Request.php) object, not Laravel's request.
> 
> Make sure that you inspect this class to see the public interface.

I had upgraded from an older version of Enso which was injecting the Laravel Request object (to pass parameters for the Query). 
I must have misunderstood the implementation. Either way it appears to be not a bug, but rather my ineptitude. 

I'm now using the Laravel Helper to acquire the request object 
```php
$this->request = request();
```
