### ISSUE TITLE
Align table headers

### ISSUE THREAD

**Issue by wbovela** [laravel-enso/tables#191]
This is  a feature request.

### Prerequisites
[ ] Are you running the latest version? -- No, currently on 3.7.2
[X] Are you reporting to the correct repository?
[X] Did you check the documentation?
[X] Did you perform a cursory search?

### Description
I would like an option that enables aligning table headers (and footers) to left, center or right.
The documentation mentions an "align" option that can be added to the table template, but adding that generates an error saying that the "align" keyword is not recognised.
The @enso-ui/tables/src/bulma//parts/TableHeader.vue file contains the "has-text-centered" style class hard coded, explaining the current behaviour.

A similar problem was described in issue #45, but the changes made there appear to have been reverted.

### Steps to Reproduce
Show any table. Headers are always centered.

### Expected behavior
Headers aligning left, center or right according to "align" setting in table template.

### Actual behavior
Headers are always centered

**Comment by aocneanu** [comment]
The `align` attribute is a working option, does not generate any errors and can be used in the `column` object within the template's `columns` array.

This option does not (never did) affect the header or the footer. It's only for the table body.

I never encountered nor imagined a scenario where having this option would be useful ... but feel free to create a PR for that.

Make sure that you follow the logic of the other attributes.

You can call the new option `header-align` and while doing it you can create a `footer-align` too.

Thanks.
