### ISSUE TITLE
Allow searching for/filter by enum

### ISSUE THREAD

**Issue by adithewonderboy** [laravel-enso/tables#192]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
It should be possible to search for an enum value inside a vue datatable
Maybe inside tables/app/Services/Data/Filters/Search.php the columns that have enums set in meta may be treated differently and be queried with their mapping from enum.

### Steps to Reproduce
Search after keyword 'Miss' inside people section here: https://www.laravel-enso.com/administration/people/

### Expected behavior
We expect to see all the persons with title 'Miss' as results.

### Actual behavior
We get persons with title 'Mr', 'Ms' and 'Miss' as results, this is unexpected

**Comment by adithewonderboy** [comment]
As a mention the solution from ticket #121 is not clear for me and I don't find Examples in the new Enso code. Thanks!

**Comment by aocneanu** [comment]
You can filter by enum using a vue-filter

[example](https://github.com/laravel-enso/examples/blob/master/src/resources/views/table/index.blade.php)

**Comment by adithewonderboy** [comment]
This is not exactly what I was hoping for, I need this functionality inside the enso table.
I mean when you enter a query in the table's search control, it should search for the enum key. 
For example when I search for "Mr" I am expecting to see all records with title=Mr. 
Currently it's possible do that only by searching for the numeric value of Mr, which is 3. From src/app/Enums/Titles.php.. 
I think you agree that this is weird for an user, to search for id's in order to get one person's title. See the example below:

![image](https://user-images.githubusercontent.com/58045802/76768657-fd95bb00-67a3-11ea-9943-b05fd826c217.png)

![image](https://user-images.githubusercontent.com/58045802/76768702-0dad9a80-67a4-11ea-961e-1fb70ac0d81e.png)

![image](https://user-images.githubusercontent.com/58045802/76768733-1c944d00-67a4-11ea-9d87-b2adf8efd91f.png)

![image](https://user-images.githubusercontent.com/58045802/76768863-4ea5af00-67a4-11ea-92d4-2f69af46c4eb.png)

![image](https://user-images.githubusercontent.com/58045802/76768953-70069b00-67a4-11ea-9280-6791c4206203.png)

Thanks!

**Comment by aocneanu** [comment]
I was not suggesting searching by id. I was suggesting adding a table filter using the enum.

Are you familiar at all with our collection of table filters?

**Comment by vmcvlad** [comment]
The table's search bar is used to query the database before fetching the results. If you wish to search for plain text, you can't use Enums for your particular columns.

As @aocneanu stated above, if you wish to filter the results based on Enum values, our filters components provide a more than reasonable solution.

**Comment by adithewonderboy** [comment]
I did not imply that one needs to search by id, this is how https://www.laravel-enso.com/ behaves on people screen. 
If you are talking about Custom Filters and Advance Filtering sections on tables, it's not very clear from the documentation how to integrate it with my code below. 
I thought this would be a straightforward approach since the adding of Enums is supported in .json template files out of the box. I thought they may be managed accordingly by the search engine without applying extended filtering
Currently my structure is  something like this:
The enum field from model template file:
![image](https://user-images.githubusercontent.com/58045802/76773441-22416100-67ab-11ea-9b81-cef986e15539.png)
And the table definition inside Index.vue:
![image](https://user-images.githubusercontent.com/58045802/76773590-66346600-67ab-11ea-8903-a32affed137f.png)

**Comment by adithewonderboy** [comment]
> The table's search bar is used to query the database before fetching the results. If you wish to search for plain text, you can't use Enums for your particular columns.
> 
> As @aocneanu stated above, if you wish to filter the results based on Enum values, our filters components provide a more than reasonable solution.

Yes, this was my aim, to query the database using the enums before filtering the results...

**Comment by vmcvlad** [comment]
Custom Filters aren't what you need either. You may use Custom Filters if you wish to send a custom params object to the Table class and interpret it in any way you want in order to filter your results. Custom Filters can be used by implementing the CustomFilter interface in your Table class. However, this is unrelated to the search bar.

**Comment by aocneanu** [comment]
@adithewonderboy 
clone [v3.6.1](https://github.com/laravel-enso/enso/tree/3.6.1)

Use the readme from that version. Put the app up and you will have access to the examples.

I thinkg that would be a good opportunity to see the filters in action.

**Comment by adithewonderboy** [comment]
That sounds good and I will do it. I managed to solve my issue adding select-filter but only to render it outside my table like this:
![image](https://user-images.githubusercontent.com/58045802/76878606-c4ca1480-687d-11ea-8c6b-98c776167b67.png)

I'm investigating how to include it inside my table(this is requested by client)

**Comment by aocneanu** [comment]
There is no out of the box way of including it in the table.

You could also use other vue-filter or enso-filter instead of a select filter, depending on the option count and app logic.
