### ISSUE TITLE
Add column visibility control for columns in template file

### ISSUE THREAD

**Issue by adithewonderboy** [laravel-enso/tables#198]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
It will be very nice and useful to have a control of column visibility inside the template file.
Currently one can set which columns to see or to hide after the table is loaded but this setting cannot be preset from the template.
Here is the section in question:
![image](https://user-images.githubusercontent.com/58045802/80605583-f2d57380-8a3b-11ea-9aa5-7b0d042499fa.png)

Let's consider someone wants the table to load with "Protocol" and "Port" hidden as default. This is not possible right now. Rogue setting is not useful because once a column is hidden, it cannot be displayed afterwards inside the table.

I was thinking something like :
![image](https://user-images.githubusercontent.com/58045802/80606029-798a5080-8a3c-11ea-8cb6-80f98fda8b81.png)
or any other name for that matter..

Thank you!

**Comment by robbykrlos** [comment]
I found this lack of functionality too, when trying to avoid showing all less important details, but some users still wanted some columns shown. I'm interested too in this or some kind of work-around.

Thank you

**Comment by aocneanu** [comment]
done

**Comment by robbykrlos** [comment]
Thanks a lot, that's very useful!

**Comment by adithewonderboy** [comment]
Many thanks!
