### ISSUE TITLE
Duplicate total row after table head

### ISSUE THREAD

**Issue by shusharin** [laravel-enso/tables#202]
This is  a **feature request**.

### Prerequisites
* [v] Are you running the latest version?
* [v] Are you reporting to the correct repository?
* [v] Did you check the documentation?
* [v] Did you perform a cursory search?

### Description

Hi!
I didn't find, how i can make total row after table head.
Steps for implementation:

1 config/enso/tables 
- add field "isDuplicateTotalsTop":  false (default)
- add field "limitDuplicateTotalsTop": 30 (default) (when 30 or more items on page - add top totals)

2 add support in template isDuplicateTotalsTop & limitDuplicateTotalsTop

3 enso-ui
- make TableTotalRow component (from builma/parts/TableFooter)
- add TotalRow in builma/parts/TableFooter & builma/parts/TableHeader

What you think about it?

**Comment by aocneanu** [comment]
I'm not sure I understand exactly how it would look and what would be the use case.

Could you provide an use case?

**Comment by shusharin** [comment]
For example:

![image](https://user-images.githubusercontent.com/5540885/83641189-d9cd5e80-a5b5-11ea-902f-615564973257.png)

**Comment by aocneanu** [comment]
@shusharin please open a PR for this.

Let's use `topTotals` and `topTotalsLimit` as props.

**Comment by shusharin** [comment]
Hi! I am on holiday now. 
Please, don't close this issue. 
Will do PR later. 

Thx
