### ISSUE TITLE
Exceptions when trying to export excel in non-erso table

### ISSUE THREAD

**Issue by nesumneno** [laravel-enso/tables#203]
This is  a **bug**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

When you try to export Excel without using the whole Enso package an exception occurs on line 207 in LaravelEnso\Tables\App\Exports\Excel.php
"Trying to get property 'entries' of non-object"
Fix: should add if($this->dataExport)

When I fixed that there is another error on line 194 again with the $this->dataExport->entries object.
Fix: should add if($this->dataExport)

### Steps to Reproduce

1. Try to export excel using non-erso vue table

### Expected behavior

Exports excel and sends notification

### Actual behavior

Exceptions

**Comment by aocneanu** [comment]
Could you open a PR for this?

**Comment by nesumneno** [comment]
Yes, no problem.
