### ISSUE TITLE
Flatpickr in filters closing when trying to use controls

### ISSUE THREAD

**Issue by nesumneno** [laravel-enso/tables#204]
This is a bug.

### Description
Flatpickr and dropdown closing after trying to use controls

### Steps to Reproduce
1. Open data table
2. Go to filters and choose "Created At"
3. Open date picker and try to change month

### Expected behavior
Changes months and years correctly

### Actual behavior
Closing all opened elements

I found some information here:
https://github.com/flatpickr/flatpickr/issues/1241

But it's about bootstrap modal and not dropdown.
I tried some fixes but with no success.

![image](https://user-images.githubusercontent.com/11031695/83412280-7fe85f80-a422-11ea-9a7c-2c42b0c9484c.png)

**Comment by aocneanu** [comment]
@raftx24 it's related to what we discussed today.

**Comment by aocneanu** [comment]
Fixed, run `yarn upgrade`
