### ISSUE TITLE
How can I change the ensotable default length from 10 to 50 on Enso?

### ISSUE THREAD

**Issue by operatorlima2go** [laravel-enso/tables#206]
This is  a **question**.

### Prerequisites
* [Y] Are you running the latest version?
* [Y] Are you reporting to the correct repository?
* [Y] Did you check the documentation?
* [Y] Did you perform a cursory search?

### Description
How can I change the ensotable default length from 10 to 50 on Enso?

### Steps to Reproduce
N/A
### Expected behavior
N/A

### Actual behavior
N/A

**Comment by aocneanu** [comment]
The only way to achieve that now would be changing the default length menu values in the config file (tables.php) to an array of values that starts with 50.

We could make use of a global and a per template option for setting the default length. You can make a PR for this but I would suggest waiting a few days for v4.

**Comment by operatorlima2go** [comment]
Awesome Thank you.
