### ISSUE TITLE
Default sorting

### ISSUE THREAD

**Issue by aocneanu** [laravel-enso/tables#211]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

We currently don't have a default sort for table queries and this can result to inconsistent results.

It would be beneficial to have a default sort by dtRowId for all queries where we don't have a default sort. When a user manually sorts by a column the default sorting must be ignored.

**Comment by Hyfos2** [comment]
Hey man.I will check it out and see how it goes.

**Comment by aocneanu** [comment]
done.
