### ISSUE TITLE
All tables with joins report string error and fail to load

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/tables#215]
This is  a **bug | feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
All tables with joins report string error and fail to load

### Steps to Reproduce
User groups and menus works but most of others fail as they use joins.

**Comment by curtisdelicata** [comment]
I think my composer was stuck on 4.0.2. Looking at 4.0.3 it looks like may fix. I'll try that now.

**Comment by curtisdelicata** [comment]
exception: "TypeError"
file: "/home/genealogia/public_html/vendor/laravel-enso/tables/src/Services/Data/Sorts/DefaultSort.php"
line: 31
message: "Return value of LaravelEnso\Tables\Services\Data\Sorts\DefaultSort::column() must be of the type string, null returned"

**Comment by curtisdelicata** [comment]
defaultSort doesn't exist in my tables config

**Comment by curtisdelicata** [comment]
Changing the get defaultSort to dtRowId fixed it for me.

**Comment by raftx24** [comment]
I guess it should have been solved, if you still have a problem please reopen this issue.
