### ISSUE TITLE
Table pagination fails when multi-select filters are applied

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/tables#217]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [?] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
When dealing with multiple selection filters, I noticed that pagination is not working when selecting as many options as it needs to exceed the number of entries per page.

![image](https://user-images.githubusercontent.com/16973022/92004381-d54a4a80-ed4a-11ea-977a-a1410d196bd6.png)

### Steps to Reproduce
1. Define a "<select-filter multiple ... " for one existing table
2. Link a source (options) and a v-model.
3. Make sure table has more entries then the result per page table setting.
3. Select all possible options from filter.
### Expected behavior
See all results as if filter was not applied with correct number of pages.

### Actual behavior
Just first page is visible.

**Comment by robbykrlos** [comment]
LE: teste with only one filter **without** multiple option, and behavior is the same.

**Comment by raftx24** [comment]
@robbykrlos could you please write your TableBuilder & request class here?

**Comment by robbykrlos** [comment]
![image](https://user-images.githubusercontent.com/16973022/92256058-deb6ec80-eedb-11ea-8167-e88a5cf4fe64.png)

```php
<?php

namespace App\Tables\Builders\Models;

use App\Models\Device;
use Illuminate\Database\Eloquent\Builder;
use LaravelEnso\Tables\Contracts\Table;

class DeviceTable implements Table
{
    protected const TemplatePath = __DIR__ . '/../../Templates/Models/devices.json';

    public function templatePath(): string
    {
        return static::TemplatePath;
    }

    public function query(): Builder
    {
        return Device::selectRaw('
            lb_devices.id,
            lb_devices.name,
            lb_devices.type,
            lb_devices.model,
            lb_devices.serial,
            lb_devices.ip,
            lb_devices.nat_ip,
            lb_devices.status,
            lb_devices.sw,
            lb_devices.health,
            lb_clusters.name as clusterName,
            lb_devices.cluster_id
        ')->join('lb_clusters', 'lb_clusters.id', '=', 'lb_devices.cluster_id');
    }
}
```

- models.clusters.options is the default options generated by enso cli
- request class ? if you mean the controller for the model tableData it's default - no changes:

```php 
<?php

namespace App\Http\Controllers\Models\Devices;

use App\Tables\Builders\Models\DeviceTable;
use Illuminate\Routing\Controller;
use LaravelEnso\Tables\Traits\Data;

class TableData extends Controller
{
    use Data;

    protected $tableClass = DeviceTable::class;
}
```

and  table json template:

```json
{
  "name": "Device",
  "routePrefix": "models.devices",
  "crtNo": false,
  "selectable": true,
  "buttons": [
    "excel",
    "create",
    "show",
    "edit",
    "destroy"
  ],
  "columns": [
    {
      "label": "Name",
      "name": "name",
      "data": "name",
      "meta": [
        "searchable",
        "sortable"
      ]
    },
    {
      "label": "Type",
      "name": "type",
      "data": "type",
      "meta": [
        "searchable",
        "sortable"
      ]
    },
    {
      "label": "Model",
      "name": "model",
      "data": "model",
      "meta": [
        "searchable",
        "sortable"
      ]
    },
    {
      "label": "Serial",
      "name": "serial",
      "data": "serial",
      "meta": [
        "searchable",
        "sortable"
      ]
    },
    {
      "label": "IP",
      "name": "ip",
      "data": "ip",
      "meta": [
        "searchable",
        "sortable"
      ]
    },
    {
      "label": "Nat IP",
      "name": "nat_ip",
      "data": "nat_ip",
      "meta": [
        "searchable",
        "sortable"
      ]
    },
    {
      "label": "Status",
      "name": "status",
      "data": "status",
      "meta": [
        "searchable",
        "sortable"
      ]
    },
    {
      "label": "Health",
      "name": "health",
      "data": "health",
      "tooltip": "STATUS",
      "meta": [
        "searchable"
      ]
    },
    {
      "label": "Cluster",
      "name": "clusterName",
      "data": "lb_clusters.name",
      "meta": [
        "searchable",
        "sortable"
      ]
    }
  ]
}
```

**Comment by robbykrlos** [comment]
Also (if you want I can open another ticket) the counter seems to count soft-deleted entries, showing 2 pages, but if I click page 2 - is basically empty (because it can be that only 10 are not deleted, and 10 are deleted) and it loads again page 1.

**Comment by robbykrlos** [comment]
> @robbykrlos could you please write your TableBuilder & request class here?

Sorry, I wasting your time. I answered initially with another example thinking will simplify things but it seems with this new simple exmaple it was working. so it means that maybe the problem lies into the builder where the SQL has something like:
```sql
return Virtual::with('pool')->selectRaw('
            lb_virtuals.id,
            lb_virtuals.name as virtualName,
            GROUP_CONCAT(DISTINCT lb_profiles.name) as "profileName",
            lb_virtuals.ip,

...  lot of fields....

6x left joins

->groupBy(
                'lb_virtuals.name'
            );

```

so maybe if you still want to pursue this, try to have something similar. If not, I'll dig deeper into it and try to find some better explanations. until then we can close this ticket.

**Comment by adithewonderboy** [comment]
Hi,
The pagination fails because the `count()` method used in vendor/laravel-enso/tables/src/Services/Data/Builders/Meta.php at line 65 fails when applied on a query which contain a groupBy clause.
In short, a count(*) on a grouped query will return the number of items that belong to each group, in your case @robbykrlos this was 1 instead of the actual number of records filtered. On the other hand, an Eloquent count() doesn't know about your query, just tells you the number of rows that were returned.

In order to fix this behavior, one must add
`$this->query->get()->count()` instead of
`$this->query->count()`

@raftx24 Can you please check this and maybe fix it in the future releases?
Thank you!

**Comment by robbykrlos** [comment]
@raftx24 would you like me to make a contribution and ask for a MR? is this solution OK for you?

**Comment by raftx24** [comment]
Hey @robbykrlos and @adithewonderboy , sorry for answering late.
this solution isn't perfect because it has a huge impact on big tables. 
we should find a better solution for fixing such queries.

**Comment by raftx24** [comment]
I guess `return $this->query->getQuery()->getCountForPagination();` in `Meta.php` will fix it but I need to discuss with adrian.

**Comment by adithewonderboy** [comment]
@raftx24 I tested my case with `return $this->query->getQuery()->getCountForPagination();` and it works nicely.
I hope you can push this fix soon, thanks!

**Comment by raftx24** [comment]
please check it again it should be fixed
