### ISSUE TITLE
Entries count <> Rows if you have deleted rows

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/tables#226]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

The entries count in table footer is wrong if you have soft deleted rows in your database.
![image](https://user-images.githubusercontent.com/7204559/95680182-ee5eda80-0bd7-11eb-8daf-7526f5bfe435.png)

### Steps to Reproduce
1. Create a table for a model which uses soft deletes
2. Delete one entry
3. Check sum row in footer

### Expected behavior

In my screenshot the footer row should be "From 1 to 12 of 12 entries"

### Actual behavior

In my screenshot the footer row is "From 1 to 12 of 14 entries"
- I have 2 soft deleted rows in table

**Comment by aocneanu** [comment]
@mauthi please test

**Comment by mauthi** [comment]
Works for me. Thx for fixing.

**Comment by aocneanu** [comment]
Unfortunately this has serious performance issues on big tables with complex queries / subqueries.

We will revert @raftx24

**Comment by aocneanu** [comment]
@mauthi please try the `fix/softDeletes` branch and report back.

@vmcvlad , @gandesc you can review too.

**Comment by mauthi** [comment]
Works perfect for my use case. Thx.

**Comment by mauthi** [comment]
Found an error:
If I use a table with join I get the following error:

`"message": "SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'deleted_at' in where clause is ambiguous (SQL: select count(*) as aggregate from `suppliers` left join `tax_types` on `suppliers`.`tax_type_id` = `tax_types`.`id` where `deleted_at` is null)",`

My used select:
```
return Supplier::select(
            \DB::raw('suppliers.id as id, suppliers.name as supplier_name, tax_types.name as tax_type_name')
        )
            ->leftJoin('tax_types', 'suppliers.tax_type_id', '=', 'tax_types.id');
```

**Comment by aocneanu** [comment]
Fixed.

**Comment by mauthi** [comment]
Tested - error is fixed.

**Comment by aocneanu** [comment]
But thinking more about it, I guess this approach is not enough. It will solve your case but won't work when you will want your query withTrashed, right?

**Comment by mauthi** [comment]
Right - if I use return `CustomerGroup::withTrashed()->withCount('customers');` I get the same amount of rows (# of rows with deleted is null)

**Comment by aocneanu** [comment]
Could you paste here your table query captured with telescope?

**Comment by mauthi** [comment]
I got the deleted rows in table but footer is wrong:
![image](https://user-images.githubusercontent.com/7204559/100421383-91848a00-3088-11eb-909c-187cc793a95d.png)

Query:
```
select
  `customer_groups`.*,
  (
    select
      count(*)
    from
      `customers`
    where
      `customer_groups`.`id` = `customers`.`customer_group_id`
      and `customers`.`deleted_at` is null
  ) as `customers_count`
from
  `customer_groups`
order by
  `customer_groups`.`id` asc
limit
  20 offset 0
```

So the total row count is not updated and if I see that correctly it's even not fetched again?

**Comment by mauthi** [comment]
And one additional thing: The delete button is also visible for deleted items and leads to a 404 (but thats not a normal use case to show deleted rows)

**Comment by aocneanu** [comment]
ok, this needs more work but I guess we're on the right path

**Comment by mauthi** [comment]
yes thx - for me it’s fixed for now :)

**Comment by mauthi** [comment]
I found another issue:

```
    public function query(): Builder
    {
        return Customer::where('post_status','<>','trash')->selectRaw('*');
    }
```

In the table I have 6 rows, one with post_status = trash
Now I get `From 1 to 5 of 6 entries` as footer.

**Comment by raftx24** [comment]
Hi @mauthi 
could you please check my commit too? 
I checked it and it worked with withTrash,...
thanks

**Comment by mauthi** [comment]
Hi @raftx24,

I just tried it.
For me it's not working for both - soft deletes and normal where statements (like described in https://github.com/laravel-enso/tables/issues/226#issuecomment-734920345)

**Comment by raftx24** [comment]
@mauthi.
I created 6 companies, and I set the first company name to `trash`(similar to your situation).
this is my `CompanyTable`
```
class CompanyTable implements Table
{
    protected const TemplatePath = __DIR__.'/../Templates/companies.json';

    public function query(): Builder
    {
        return Company::where('name', '<>', 'trash')->selectRaw('*');
    }

    public function templatePath(): string
    {
        return static::TemplatePath;
    }
}
```
and this is the result.
![image](https://user-images.githubusercontent.com/10864136/101522358-547b9a00-399c-11eb-839e-962edf83b76a.png)

**Comment by mauthi** [comment]
I tried if again (with your branch `/softDeletesWithApplyingScopes`):

query():
`return CustomerGroup::where('name', 'like', '%an%');`

Result:
![image](https://user-images.githubusercontent.com/7204559/101524488-47ee4600-398a-11eb-85be-b0bc3c1be57e.png)

**Comment by raftx24** [comment]
@mauthi  I guess there is another problem with your table. because I used this table(10 companies with (8 + 2 deleted))
![image](https://user-images.githubusercontent.com/10864136/101525287-56dff300-39a0-11eb-8fcf-1a575138e354.png)

and I tried to simulate your situation with the following Table class
```
class CompanyTable implements Table
{
    protected const TemplatePath = __DIR__.'/../Templates/companies.json';

    public function query(): Builder
    {
        return Company::where('name', 'like', '%a%');
    }

    public function templatePath(): string
    {
        return static::TemplatePath;
    }
}
```
and I got this result.
![image](https://user-images.githubusercontent.com/10864136/101525482-a1fa0600-39a0-11eb-86f6-bc40656df4a9.png)

-------
Maybe your cache is enabled and you cannot see the current `count`.

**Comment by mauthi** [comment]
Hi again,

Thx for the hint with the cache - I deleted it with `php artisan enso:tables:clear` and now it looks fine.
But the question is how this cache works and why this is enabled? Do you have a short explaination for me?

**Comment by raftx24** [comment]
You're welcome.
Yes, from [docs](https://docs.laravel-enso.com/backend/tables.html#configuration)

> count, is a boolean, default is true. When counting the number of results for the table,
a count query has to be performed and for costly queries there can be quite a performance improvement if the count result is cached.
> Note that if caching the count, you should use the TableCache trait on the main/base model, so that the count cache is invalidated if when a model is created or deleted.

**Comment by mauthi** [comment]
Thx - I will check this.

So we can close this topic?

**Comment by mauthi** [comment]
@aocneanu the fix of @raftx24 works for me (as written above) - is there a reason why his PR is still open or didn't you have time to check? If you need any feedback or help to test this feel free to ask.

**Comment by aocneanu** [comment]
merged
