### ISSUE TITLE
Wrong table pagination count using soft-delete trait 

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/tables#241]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
This is somehow related to "_Table pagination fails when multi-select filters are applied_" #217, where the issue still persists and has a wider effect.

I have the following App\Tables\Builders\ModelTable.php file:
```php
...
public function query(): Builder
{
   return Model::selectRaw('
            model.id,
            model.name as rserverName,
            model.ip,
            model.description,
            model.status
        ');
}
...
```
So as you can see, it's a simple query, no joins, no aggregation, no scope method call, no nothing.

My Model table json (App\Tables\Templates\models.json\) definition has :
```json
"countCache": false,
```

My Model class has these traits used:
```php
 use HasFactory, SoftDeletes, TableCache;
```

I have a total of 20 entries in my DB, from which 2 are soft-deleted:
![image](https://user-images.githubusercontent.com/16973022/101630652-da92f180-3a2b-11eb-89e5-30fc2a376885.png)

When loading the table, I see 2 pages (with 10 rows per page):
Page 1:
![image](https://user-images.githubusercontent.com/16973022/101630827-12019e00-3a2c-11eb-86d9-f432be4e0093.png)
Page 2:
![image](https://user-images.githubusercontent.com/16973022/101630889-22b21400-3a2c-11eb-9e91-6470b49ad973.png)

As you can see, page 2 has 2 missing rows (which are reflected also in the actual table rows) but the total count is still 20, as if the soft-delete is taken in account when loading the table data, but not when doing the counting for pagination.

Even more, if I add a 21st entry in DB, I will get page 3 shown, but not accessible, since there are no visible entries to be shown there. A redirect to page 1 is done.

Could still be something from here:
``vendor/laravel-enso/tables/src/Services/Data/Builders/Meta.php`` or even  ``vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php``

**Comment by raftx24** [comment]
Hi @robbykrlos,
could you please test it with this [fix/softDeletesWithApplyingScopes ](https://github.com/laravel-enso/tables/pull/240)?  
thank you

**Comment by mauthi** [comment]
And call `php artisan enso:tables:clear` to delete local table cache

**Comment by robbykrlos** [comment]
Yes. Seems to be working with fix/softDeletesWithApplyingScopes. I see the fix is quite recent :-) 
Thank you & sorry I did not searched more - apparently I used some keywords that did not show #226

Duplicated.

Fixed by _Entries count <> Rows if you have deleted rows_ #226
