### ISSUE TITLE
Hide custom button if route is not available

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/tables#242]
This is  a **question**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

For my customers table I have defined an additional row button:

```
{
        "type": "row",
        "icon": "dollar-sign",
        "class": "is-row-button",
        "event": "load-invoices"
    }

```

The event method is the following:

```
loadInvoices(row) {
            this.$router.push({
                name: 'billing.invoices.index',
                params: {
                    id: row.id,
                    filterType: 'customer',
                },
            });
        },
```

Now I have the problem, that the button should only be visible for users who have access to the `billing.invoices.index` route.

My question:
Is there a possibility to show the button only if user has right to view  `billing.invoices.index`?

Thx in advance for your help.

**Comment by aocneanu** [comment]
Hi @mauthi ,

Look at the data-import table (json & builder)

**Comment by mauthi** [comment]
Thx - works perfect.
