### ISSUE TITLE
Reload table after job is finished

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/tables#245]
This is  a **question**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Is there a possibility to trigger reload of a single table from backend after a job is finished?

Use case:
- I use a table to show invoices
- In the table I have one column to show if the invoice was sent to customer and when
- I have a row action to trigger the send invoice job
- After the job is finished I would like the related cell or row or table to show the right info in frontend

Does this make sense and if yes do you use such a pattern somewhere?

**Comment by aocneanu** [comment]
Look at how the IO package is built, or notifications.

You can build your own feature by registering a new notifications channel in BE, a custom component in the FE in the page containing the table that listens to the channel. Once you send an invoice you send a notification from the BE and if the page is still active, once the notification is received you reload the table.

**Comment by aocneanu** [comment]
You can also look at how the tasks package is working, maybe it's simpler to follow

**Comment by mauthi** [comment]
Thx for your answers.

> You can also look at how the tasks package is working, maybe it's simpler to follow
It would be nice if you can add a few more infos after which action the notification is fired and on which page in frontend something happens if the page is still active. 

Thx in advance.

**Comment by raftx24** [comment]
Hi @mauthi.
there is an Event in tasks([here](https://github.com/laravel-enso/tasks/blob/master/src/Events/Task.php)). it is dispatched when the number of tasks is changed([here](https://github.com/laravel-enso/tasks/blob/master/src/Observers/Task.php#L28)). and there is a listener on FE([here](https://github.com/enso-ui/tasks/blob/master/src/core/components/navbar/Tasks.vue#L78)), that updates the tasks. also, note that you need to have ServiceProvider too([here](https://github.com/laravel-enso/tasks/blob/master/src/WebsocketServiceProvider.php#L13)).
I guess you will have the completely same things, but you need to update the table in the FE.

**Comment by aocneanu** [comment]
@mauthi can we close this?

**Comment by mauthi** [comment]
@aocneanu yes, thx.
If I need anything I will come back to you.
