### ISSUE TITLE
Static table data - non DB stored (question)

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/tables#250]
This is  a **quesiton**.

Hi,

How would you use an enso-table if you want to display non-DB-stored data. Is there an existing example?

Let's say I have a configuration file (php array, xml etc) that I also want to list inside a table, with search/sorting support.

Existing Table Builders work with rawSelects, and search and sorting is done based on queries. 

My initial impulse is to mock a virtual table with my configuration file to work around this query restriction. 

Thoughts?

**Comment by aocneanu** [comment]
I have thought about this in the past and I believe the best way would be building a separate component (core table) that would use only the needed features for an FE only table on one hand, and a BE service that would receive an array and "build" the data based on the existing json template system.

**Comment by robbykrlos** [comment]
Thanks!
