### ISSUE TITLE
Reusing tables with slight variations (question)

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/tables#251]
This is  a **question**.

Hi,

Is there a way to **slightly** change a table rendering from the JSON in different situations?
Ex: I want to use the same model table (dataTable, initTable, <models>.json etc) in 2 places. 
But I want in some case the Excel button to be hidden. Or a column to be/or not to be clickable.

At the moment I see a way only by using different table json file with controllers etc.

Thank you,

**Comment by robbykrlos** [comment]
Anyone?

**Comment by aocneanu** [comment]
The only solution right now is using two templates and doing a ternary or something in the table builder class.

**Comment by robbykrlos** [comment]
thank you @aocneanu
