### ISSUE TITLE
Strange  Argument 1 passed to LaravelEnso\Tables\Services\Template::load() must be an instance of LaravelEnso\Helpers\Services\Obj, Error

### ISSUE THREAD

**Issue by Schwenniii** [laravel-enso/tables#253]
This is  a **bug?**.

### Prerequisites
* [x ] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
* [ x] Did you check the documentation?
* [ x] Did you perform a cursory search?

### Description
i have one Project on 3 Servers. all 3 runs with apache2 and php7.4
on the production server i get this error message for all table init requests: 

production.ERROR: Argument 1 passed to LaravelEnso\Tables\Services\Template::load() must be an instance of LaravelEnso\Helpers\Services\Obj, instance of __PHP_Incomplete_Class given, called in /vendor/laravel-enso/tables/src/Services/TemplateLoader.php on line 50

i have delete cache files reupload again nothing helps.

### Actual behavior
table init not work

**Comment by gandesc** [comment]
Hi Schwenniii,

We use the same package on multiple projects/servers and so far, have not encountered this issue.

Judging by the error details, as well as the fact that you have the same code working on 2 out of 3 servers, suggests an issue with the server/apache/deployment/dependencies setup.
