### ISSUE TITLE
Toastr on delete (Tables)

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/tables#260]
This is  a **Question**.

Hi,

I'm having trouble to realize if we have a local issue, or it's "as it should works in Enso.". I cannot test this while Enso's demo user doesn't have delete permissions.

So, main question is: Should table delete action (row action from TableBody -> actionEvents , destroy.php controller) display a toastr?

We're confused, because:
- we remember some time ago there was a toastr for some table actions.
- we see the same response - JSON, { message: some texts } - on Forms, and Tables. 
- same DELETE request (same json response) returns a toastr on form delete, not on table delete.

I wanted to ask first, before I start investigating.

Thanks!

**Comment by gandesc** [comment]
Hi Robert,

It should display a confirmation modal, while after confirmation & deletion, no toastr is shown and the table reloads its data.

**Comment by robbykrlos** [comment]
@gandesc Ok, thanks.
